[package]
name = "pathtr"
version = "0.1.0"
authors = ["Jonathan Karlsson <karlsjona@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
cpuprofiler = "*"
image = "*"
rand = "*"
rand_xorshift = "*"
sdl2 = "*"
threadpool = "*"
time = "*"
